### ISSUE TITLE
macOS backup automation

### ISSUE THREAD

**Issue by whatageareyouin** [rwoodpecker/KoboBackup#12]
Backup automation is supported on Linux. Let's add support for macOS

**Comment by rwoodpecker** [comment]
Doesn't look like there is a way to monitor for media insertions on OSX in python unfortunately. pyudev is Linux only. Could set up a watcher script that probes df -h every x minutes to see if the volume is mounted and could also be run as a cron task, but neither are a great solution if the device is only plugged in for a short amount of time occasionally.
