### ISSUE TITLE
Introduce macOS notifications and improve Linux notifications

### ISSUE THREAD

**Issue by whatageareyouin** [rwoodpecker/KoboBackup#17]
Currently, Linux systems will open a notification when:
1. a KOBOeReader is connected;
2. a backup is complete.

Let's do that for macOS as well.

We should also call the Linux notifications properly. 
- In `automation/watcher_script.py`, we need to check which platform system we are on and then call the relevant `subprocess` to open the notification.
- In `kobo_backup.py` we also need to do that to notify the backup has completed.

**Comment by whatageareyouin** [comment]
@rwoodpecker are you happy to tackle the small Linux improvements while you develop the feature for macOS?

**Comment by rwoodpecker** [comment]
Implemented the second part of this per #25 and previous PRs. Unfortunately it doesn't look like the OSX component will be possible.
