### ISSUE TITLE
Implement a configuration file

### ISSUE THREAD

**Issue by rwoodpecker** [rwoodpecker/KoboBackup#22]
This would be useful when the script is being called automatically and not being passed arguments from the CLI. Would need to support #14 compression, a user configurable backup path and could be used to specify number of backups to keep for #6 backup rotation. I think current defaults from the script are suitable and could be used to generate a config file on first run.

Best spot for it would probably be ~/.config - is that good for Linux @whatageareyouin?

**Comment by whatageareyouin** [comment]
Yeah sounds good!

**Comment by rwoodpecker** [comment]
Implemented in #27.
