### ISSUE TITLE
Add argparse

### ISSUE THREAD

**Issue by rwoodpecker** [rwoodpecker/KoboBackup#7]
Let's implement argparse to improve handling of arguments. See https://docs.python.org/3/howto/argparse.html.

**Comment by rwoodpecker** [comment]
@whatageareyouin I think we should implement this before compression in #5

**Comment by whatageareyouin** [comment]
I have created a branch `arg_parsing`. It just has some preliminary organisational changes to make it easier to implement argparse, taken from [here](https://www.reddit.com/r/learnpython/comments/3do2wr/comment/ct71t31/).

Enjoy. 😎

**Comment by rwoodpecker** [comment]
Closed in #9.
